import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';import {q,pool} from './db.js';import {ensureAdmin} from './auth.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const schema=fs.readFileSync(path.join(root,'../../database/schema.sql'),'utf8');
await q(schema); await ensureAdmin();
const cats=[['🛒','التجارة والتسوق','بقاليات وألبسة وإلكترونيات'],['🔧','المهن والخدمات','كهربائي وسباك ونجار'],['🍔','الطعام والضيافة','مطاعم وأفران ومقاهي'],['🏥','الصحة','أطباء وصيدليات ومختبرات'],['🚗','السيارات والمواصلات','تكاسي وسرافيس وميكانيك'],['🎓','التعليم','مدارس ومعاهد وطباعة'],['💼','الأعمال والمكاتب','محاسبة ومحاماة وتصميم'],['🧵','الخياطة والألبسة','تفصيل وتطريز وإصلاح'],['🏛️','المؤسسات العامة','بلدية وجمعيات ومساجد'],['📢','الإعلانات','بيع ووظائف وعروض'],['🚨','الطوارئ','إسعاف وإطفاء ودفاع مدني'],['💱','العملات والمعادن','أسعار وتحديثات'],['🌤️','الطقس','أرمناز الآن والتوقعات'],['🕌','الصلاة','المواقيت والصلاة القادمة'],['📿','الأذكار','الصباح والمساء والنوم'],['✨','التسبيح','عداد وأهداف جلسات']];
for(let i=0;i<cats.length;i++) await q('INSERT INTO categories(name,icon,description,sort_order) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING', [cats[i][1],cats[i][0],cats[i][2],i]);
const emergency=[['🚑','الإسعاف','108'],['🚒','الإطفاء','113'],['👮','الشرطة','112'],['🛡️','الدفاع المدني','110']]; for(let i=0;i<emergency.length;i++) await q('INSERT INTO emergency_contacts(name,icon,phone,sort_order) SELECT $1,$2,$3,$4 WHERE NOT EXISTS(SELECT 1 FROM emergency_contacts WHERE name=$1)',emergency[i].map((x,j)=>j===0?x:x).concat(i));
const serviceCat=await q("SELECT id FROM categories WHERE name='الصحة' LIMIT 1"); const cid=serviceCat.rows[0]?.id; if(cid){const s=await q("SELECT id FROM services WHERE name='صيدلية الشفاء' LIMIT 1"); if(!s.rowCount){const x=await q("INSERT INTO services(category_id,name,description,phone,address_text,enabled) VALUES($1,$2,$3,$4,$5,true) RETURNING id",[cid,'صيدلية الشفاء','صيدلية مناوبة في أرمناز','0000 000 000','الشارع الرئيسي · قرب الجامع الكبير']); await q('INSERT INTO pharmacies(service_id) VALUES($1)',[x.rows[0].id]);}}
await q("INSERT INTO settings(key,value) VALUES('site_name','أرمناز'),('city','أرمناز'),('version','2.0.0') ON CONFLICT(key) DO NOTHING");
await q("INSERT INTO adhkar(category,text,repeat_count,sort_order) SELECT * FROM (VALUES ('الصباح','أصبحنا وأصبح الملك لله',1,1),('المساء','أمسينا وأمسى الملك لله',1,1),('النوم','باسمك اللهم أموت وأحيا',1,1)) v(category,text,repeat_count,sort_order) WHERE NOT EXISTS(SELECT 1 FROM adhkar)");
console.log('Seed complete');await pool.end();
