CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) UNIQUE NOT NULL, password_hash TEXT NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'admin', enabled BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS categories (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, icon VARCHAR(20), description TEXT, sort_order INT DEFAULT 0, enabled BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS services (id BIGSERIAL PRIMARY KEY, category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL, name VARCHAR(160) NOT NULL, description TEXT, phone VARCHAR(40), whatsapp VARCHAR(40), address_text TEXT, latitude NUMERIC(10,7), longitude NUMERIC(10,7), keywords TEXT, status_override VARCHAR(30), enabled BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS service_hours (id BIGSERIAL PRIMARY KEY, service_id BIGINT REFERENCES services(id) ON DELETE CASCADE, weekday SMALLINT NOT NULL CHECK(weekday BETWEEN 0 AND 6), opens_at TIME, closes_at TIME, closed BOOLEAN DEFAULT FALSE, UNIQUE(service_id,weekday));
CREATE TABLE IF NOT EXISTS emergency_contacts (id BIGSERIAL PRIMARY KEY, name VARCHAR(120) NOT NULL, icon VARCHAR(20), phone VARCHAR(40) NOT NULL, sort_order INT DEFAULT 0, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS pharmacies (id BIGSERIAL PRIMARY KEY, service_id BIGINT UNIQUE REFERENCES services(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS duties (id BIGSERIAL PRIMARY KEY, service_type VARCHAR(50) NOT NULL, service_id BIGINT REFERENCES services(id) ON DELETE CASCADE, duty_date DATE NOT NULL, starts_at TIME, ends_at TIME, status VARCHAR(30), notes TEXT, UNIQUE(service_type,service_id,duty_date));
CREATE TABLE IF NOT EXISTS currencies (id BIGSERIAL PRIMARY KEY, code VARCHAR(10) NOT NULL, name VARCHAR(80), buy NUMERIC, sell NUMERIC, source TEXT, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS metals (id BIGSERIAL PRIMARY KEY, name VARCHAR(80), price NUMERIC, unit VARCHAR(30), source TEXT, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS weather_cache (id BIGSERIAL PRIMARY KEY, city VARCHAR(100) NOT NULL, temperature NUMERIC, description TEXT, humidity NUMERIC, wind_kmh NUMERIC, payload JSONB, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS prayer_cache (id BIGSERIAL PRIMARY KEY, city VARCHAR(100) NOT NULL, date DATE NOT NULL, timings JSONB NOT NULL, source TEXT, updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(city,date));
CREATE TABLE IF NOT EXISTS announcements (id BIGSERIAL PRIMARY KEY, title VARCHAR(200) NOT NULL, body TEXT, type VARCHAR(40), published BOOLEAN DEFAULT FALSE, starts_at TIMESTAMPTZ, ends_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS adhkar (id BIGSERIAL PRIMARY KEY, category VARCHAR(30), text TEXT NOT NULL, repeat_count INT DEFAULT 1, sort_order INT DEFAULT 0, enabled BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS settings (key VARCHAR(120) PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS visits (id BIGSERIAL PRIMARY KEY, path TEXT, user_agent TEXT, visited_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_services_category ON services(category_id);
CREATE INDEX IF NOT EXISTS idx_services_enabled ON services(enabled);
CREATE INDEX IF NOT EXISTS idx_duties_date ON duties(duty_date);
CREATE INDEX IF NOT EXISTS idx_announcements_published ON announcements(published);
